version: '3.9'

services:   
  back:
    hostname: back
    container_name: back
    image: cosmtrek/air
    restart: unless-stopped
    command: ["-c", "/app/.air.toml"]
    working_dir: /app
    ports:
      - 10000:10000
    volumes:
      - ./back/:/app
    network_mode: "host"
  
  front:
    hostname: front
    container_name: front
    image: node
    restart: unless-stopped
    command: bash -c "npm install && npm run dev -- --port=5000"
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./front/:/app
    network_mode: "host"